export const AllProducts = [
  // _____________smartPhone________________
  {
    id: 1,
    categories: "smartPhone",
    title: "MacBook Pro 14-inch (M2)",
    image:
      "https://i.postimg.cc/qqWgV087/1.jpg?w=300&format=webp&quality=80 ?w=300&format=webp&quality=80",
    rating: 4.9,
    price: 1999,
    oldPrice: 2299,
  },
  {
    id: 2,
    categories: "smartPhone",
    title: "Dell XPS 15",
    image:
      "https://i.postimg.cc/J7FsB39W/2.jpg?w=300&format=webp&quality=80 ?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 1499,
    oldPrice: 1699,
  },
  {
    id: 3,
    categories: "smartPhone",
    title: "iPhone 15 Pro Max",
    image: "https://i.postimg.cc/x8ByJ5hG/1.jpg ?w=300&format=webp&quality=80",
    rating: 4.8,
    price: 1199,
    oldPrice: 1399,
  },
  {
    id: 4,
    categories: "smartPhone",
    title: "Samsung Galaxy S24 Ultra",
    image: "https://i.postimg.cc/BZ7hfcYn/2.jpg ?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 1099,
    oldPrice: 1299,
  },
  {
    id: 5,
    categories: "smartPhone",
    title: "Asus ROG Gaming Laptop",
    image: "https://i.postimg.cc/pX9sWh4Y/3.jpg?w=300&format=webp&quality=80",
    rating: 4.5,
    price: 1799,
    oldPrice: 1999,
  },
  {
    id: 6,
    categories: "smartPhone",
    title: "MSI Optix Gaming Monitor",
    image: "https://i.postimg.cc/LsVTCzgR/4.jpg ?w=300&format=webp&quality=80",
    rating: 4.4,
    price: 399,
    oldPrice: 499,
  },
  {
    id: 7,
    categories: "smartPhone",
    title: "LG UltraWide Monitor",
    image: "https://i.postimg.cc/Px3MhTMR/5.jpg ?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 699,
    oldPrice: 849,
  },
  {
    id: 8,
    categories: "smartPhone",
    title: "Logitech MX Master 3 Mouse",
    image: "https://i.postimg.cc/prSkQRhF/6.jpg ?w=300&format=webp&quality=80",
    rating: 4.8,
    price: 99,
    oldPrice: 129,
  },
  {
    id: 9,
    categories: "smartPhone",
    title: "Razer BlackWidow V3 Keyboard",
    image:
      "https://i.postimg.cc/6prLqd0R/7.jpg ?w=300&format=webp&quality=80  ",
    rating: 4.6,
    price: 149,
    oldPrice: 179,
  },
  {
    id: 10,
    categories: "smartPhone",
    title: "Corsair K100 RGB Mechanical Keyboard",
    image: "https://i.postimg.cc/vBN5kXYR/8.jpg?w=300&format=webp&quality=80 ",
    rating: 4.9,
    price: 199,
    oldPrice: 229,
  },
  {
    id: 11,
    categories: "smartPhone",
    title: "Sony WH-1000XM5 Headphones",
    image: "https://i.postimg.cc/K4XBvz3J/9.jpg?w=300&format=webp&quality=80 ",
    rating: 4.8,
    price: 349,
    oldPrice: 399,
  },
  {
    id: 12,
    categories: "smartPhone",
    title: "AirPods Pro 2nd Gen",
    image: "https://i.postimg.cc/XJ7gTp95/10.jpg?w=300&format=webp&quality=80 ",
    rating: 4.7,
    price: 249,
    oldPrice: 299,
  },
  {
    id: 13,
    categories: "smartPhone",
    title: "Anker 737 Power Bank (PowerCore 24K)",
    image: "https://i.postimg.cc/cLyBdDQ0/11.jpg?w=300&format=webp&quality=80 ",
    rating: 4.9,
    price: 149,
    oldPrice: 179,
  },
  {
    id: 14,
    categories: "smartPhone",
    title: "Canon EOS R6 Mark II",
    image: "https://i.postimg.cc/kMHypMGV/12.jpg?w=300&format=webp&quality=80 ",
    rating: 4.9,
    price: 2499,
    oldPrice: 2699,
  },
  {
    id: 15,
    categories: "smartPhone",
    title: "DJI Mavic Air 2 Drone",
    image: "https://i.postimg.cc/65DYy6Ns/13.jpg?w=300&format=webp&quality=80 ",
    rating: 4.8,
    price: 799,
    oldPrice: 999,
  },
  {
    id: 16,
    categories: "smartPhone",
    title: "Xbox Series X Console",
    image: "https://i.postimg.cc/bwkLbXzZ/14.jpg?w=300&format=webp&quality=80 ",
    rating: 4.7,
    price: 499,
    oldPrice: 549,
  },
  {
    id: 17,
    categories: "smartPhone",
    title: "PlayStation 5",
    image: "https://i.postimg.cc/prmJL4GX/15.jpg?w=300&format=webp&quality=80 ",
    rating: 4.9,
    price: 499,
    oldPrice: 549,
  },
  {
    id: 18,
    categories: "smartPhone",
    title: "Elgato Stream Deck XL",
    image: "https://i.postimg.cc/R0G7Q42Z/16.jpg?w=300&format=webp&quality=80 ",
    rating: 4.7,
    price: 249,
    oldPrice: 299,
  },
  {
    id: 19,
    categories: "smartPhone",
    title: "GoPro HERO10 Black",
    image: "https://i.postimg.cc/nr9qJ7rX/17.jpg?w=300&format=webp&quality=80 ",
    rating: 4.6,
    price: 399,
    oldPrice: 499,
  },
  {
    id: 20,
    categories: "smartPhone",
    title: "Apple iPad Pro 12.9” (M2)",
    image: "https://i.postimg.cc/YqmxKcLd/19.jpg?w=300&format=webp&quality=80 ",
    rating: 4.8,
    price: 1099,
    oldPrice: 1249,
  },

  // ______________featuredPhone _______________
  {
    id: 21,
    categories: "featuredPhone",
    title: "featuredPhone Model 1",
    image: "https://i.postimg.cc/90vm6wwF/1.jpg?w=300&format=webp&quality=80",
    rating: 4.5,
    price: 59,
    oldPrice: 79,
  },
  {
    id: 22,
    categories: "featuredPhone",
    title: "featuredPhone Model 2",
    image: "https://i.postimg.cc/g2pXj1rc/10.jpg?w=300&format=webp&quality=80",
    rating: 4.4,
    price: 69,
    oldPrice: 89,
  },
  {
    id: 23,
    categories: "featuredPhone",
    title: "featuredPhone Model 3",
    image: "https://i.postimg.cc/L4qZbzrS/11.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 75,
    oldPrice: 95,
  },
  {
    id: 24,
    categories: "featuredPhone",
    title: "featuredPhone Model 4",
    image: "https://i.postimg.cc/MKQKy5gc/12.jpg?w=300&format=webp&quality=80",
    rating: 4.3,
    price: 65,
    oldPrice: 85,
  },
  {
    id: 25,
    categories: "featuredPhone",
    title: "featuredPhone Model 5",
    image: "https://i.postimg.cc/RF2qBDjB/13.jpg?w=300&format=webp&quality=80",
    rating: 4.5,
    price: 79,
    oldPrice: 99,
  },
  {
    id: 26,
    categories: "featuredPhone",
    title: "featuredPhone Model 6",
    image: "https://i.postimg.cc/x1Pkzgbv/14.jpg?w=300&format=webp&quality=80",
    rating: 4.4,
    price: 85,
    oldPrice: 105,
  },
  {
    id: 27,
    categories: "featuredPhone",
    title: "featuredPhone Model 7",
    image: "https://i.postimg.cc/W4Wh938t/15.jpg?w=300&format=webp&quality=80",
    rating: 4.5,
    price: 70,
    oldPrice: 90,
  },
  {
    id: 28,
    categories: "featuredPhone",
    title: "featuredPhone Model 8",
    image: "https://i.postimg.cc/vmQYwsT9/16.jpg?w=300&format=webp&quality=80",
    rating: 4.3,
    price: 55,
    oldPrice: 75,
  },
  {
    id: 29,
    categories: "featuredPhone",
    title: "featuredPhone Model 9",
    image: "https://i.postimg.cc/N0pggz2n/17.jpg?w=300&format=webp&quality=80",
    rating: 4.2,
    price: 65,
    oldPrice: 85,
  },
  {
    id: 30,
    categories: "featuredPhone",
    title: "featuredPhone Model 10",
    image: "https://i.postimg.cc/d13JDj8V/18.jpg?w=300&format=webp&quality=80",
    rating: 4.4,
    price: 75,
    oldPrice: 95,
  },
  {
    id: 31,
    categories: "featuredPhone",
    title: "featuredPhone Model 11",
    image: "https://i.postimg.cc/7Z1HR6Hw/2.jpg?w=300&format=webp&quality=80",
    rating: 4.3,
    price: 60,
    oldPrice: 80,
  },
  {
    id: 32,
    categories: "featuredPhone",
    title: "featuredPhone Model 12",
    image: "https://i.postimg.cc/nhfVT7t3/3.jpg?w=300&format=webp&quality=80",
    rating: 4.5,
    price: 65,
    oldPrice: 85,
  },
  {
    id: 33,
    categories: "featuredPhone",
    title: "featuredPhone Model 13",
    image: "https://i.postimg.cc/gJ7mhLDq/4.jpg?w=300&format=webp&quality=80",
    rating: 4.4,
    price: 72,
    oldPrice: 92,
  },
  {
    id: 34,
    categories: "featuredPhone",
    title: "featuredPhone Model 14",
    image: "https://i.postimg.cc/T1WGJ2N8/5.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 68,
    oldPrice: 88,
  },
  {
    id: 35,
    categories: "featuredPhone",
    title: "featuredPhone Model 15",
    image: "https://i.postimg.cc/1z58c6pL/6.jpg?w=300&format=webp&quality=80",
    rating: 4.3,
    price: 66,
    oldPrice: 86,
  },
  {
    id: 36,
    categories: "featuredPhone",
    title: "featuredPhone Model 16",
    image: "https://i.postimg.cc/PrYvtdXF/7.jpg?w=300&format=webp&quality=80",
    rating: 4.5,
    price: 80,
    oldPrice: 100,
  },
  {
    id: 37,
    categories: "featuredPhone",
    title: "featuredPhone Model 17",
    image: "https://i.postimg.cc/kMkt32mb/8.jpg?w=300&format=webp&quality=80",
    rating: 4.4,
    price: 70,
    oldPrice: 90,
  },
  {
    id: 38,
    categories: "featuredPhone",
    title: "featuredPhone Model 18",
    image: "https://i.postimg.cc/8sQGK8x7/9.jpg?w=300&format=webp&quality=80",
    rating: 4.3,
    price: 69,
    oldPrice: 89,
  },

  // ______________Laptop_________________
  {
    id: 39,
    categories: "laptop",
    title: "Laptop Model 1",
    image:
      "https://i.postimg.cc/2SmQM0pJ/alex-knight-j4uu-Kn-N43-M-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 899,
    oldPrice: 1099,
  },
  {
    id: 40,
    categories: "laptop",
    title: "Laptop Model 2",
    image:
      "https://i.postimg.cc/P54Wj1Tq/andras-vas-Bd7g-Nn-WJBk-U-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 999,
    oldPrice: 1199,
  },
  {
    id: 41,
    categories: "laptop",
    title: "Laptop Model 3",
    image:
      "https://i.postimg.cc/SsjRMhW8/ben-kolde-bs2-Ba7t69m-M-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.5,
    price: 899,
    oldPrice: 1049,
  },
  {
    id: 42,
    categories: "laptop",
    title: "Laptop Model 4",
    image:
      "https://i.postimg.cc/GpXxkG5f/ben-kolde-t9-Dooibg-MEk-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.8,
    price: 1099,
    oldPrice: 1299,
  },
  {
    id: 43,
    categories: "laptop",
    title: "Laptop Model 5",
    image:
      "https://i.postimg.cc/QVZdwKvk/bram-naus-N1g-UD-d-Cv-JE-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.4,
    price: 949,
    oldPrice: 1099,
  },
  {
    id: 44,
    categories: "laptop",
    title: "Laptop Model 6",
    image:
      "https://i.postimg.cc/jSrcKsfM/bram-naus-n8-Qb1-ZAk-K88-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.5,
    price: 999,
    oldPrice: 1199,
  },
  {
    id: 45,
    categories: "laptop",
    title: "Laptop Model 7",
    image:
      "https://i.postimg.cc/ncm26sXs/carlos-muza-hpj-Sk-U2-UYSU-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 1050,
    oldPrice: 1249,
  },
  {
    id: 46,
    categories: "laptop",
    title: "Laptop Model 8",
    image:
      "https://i.postimg.cc/YqQNdJPY/christin-hume-mf-B1-B1s4s-Mc-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 1150,
    oldPrice: 1349,
  },
  {
    id: 47,
    categories: "laptop",
    title: "Laptop Model 9",
    image:
      "https://i.postimg.cc/LX7kWRRB/christopher-gower-m-HRf-Lhg-ABo-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 1025,
    oldPrice: 1199,
  },
  {
    id: 48,
    categories: "laptop",
    title: "Laptop Model 10",
    image:
      "https://i.postimg.cc/DZmd5mVw/crew-4-Hg8-LH9-Hoxc-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.4,
    price: 975,
    oldPrice: 1150,
  },
  {
    id: 49,
    categories: "laptop",
    title: "Laptop Model 11",
    image:
      "https://i.postimg.cc/cJF6CH80/daniel-korpai-Hy-Twtsk8-Xq-A-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 1100,
    oldPrice: 1299,
  },
  {
    id: 50,
    categories: "laptop",
    title: "Laptop Model 12",
    image:
      "https://i.postimg.cc/XvjgGQQF/dell-8pb7-Hq539-Zw-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.8,
    price: 1250,
    oldPrice: 1450,
  },
  {
    id: 51,
    categories: "laptop",
    title: "Laptop Model 13",
    image:
      "https://i.postimg.cc/ZndPtg5k/glenn-carstens-peters-npx-XWg-Q33-ZQ-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.5,
    price: 950,
    oldPrice: 1099,
  },
  {
    id: 52,
    categories: "laptop",
    title: "Laptop Model 14",
    image:
      "https://i.postimg.cc/qBhx3tXm/howard-bouchevereau-RSCir-J70-NDM-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.4,
    price: 899,
    oldPrice: 1049,
  },
  {
    id: 53,
    categories: "laptop",
    title: "Laptop Model 15",
    image:
      "https://i.postimg.cc/7LZgYbZn/kari-shea-1-SAnr-Ixw5-OY-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.5,
    price: 970,
    oldPrice: 1120,
  },
  {
    id: 54,
    categories: "laptop",
    title: "Laptop Model 16",
    image:
      "https://i.postimg.cc/v8JLLQ0G/maxim-hopman-Hin-rzh-Od-Ws-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 1000,
    oldPrice: 1180,
  },
  {
    id: 55,
    categories: "laptop",
    title: "Laptop Model 17",
    image:
      "https://i.postimg.cc/G3Vz7Pmw/nordwood-themes-sg8n-Xmp-WDM-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 1080,
    oldPrice: 1270,
  },
  {
    id: 56,
    categories: "laptop",
    title: "Laptop Model 18",
    image:
      "https://i.postimg.cc/0ydfyLdP/samantha-borges-g-Xs-J9-Ywb5as-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.5,
    price: 920,
    oldPrice: 1040,
  },
  {
    id: 57,
    categories: "laptop",
    title: "Laptop Model 19",
    image:
      "https://i.postimg.cc/wvPv5GVr/sincerely-media-ylve-Rp-Z8-L1s-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 960,
    oldPrice: 1100,
  },
  {
    id: 58,
    categories: "laptop",
    title: "Laptop Model 20",
    image:
      "https://i.postimg.cc/J0khp5Yz/unsplash-Nu-FUbft-Uu-s-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.8,
    price: 1120,
    oldPrice: 1310,
  },

  //  __________smart watch_____________
  {
    id: 59,
    categories: "smart watch",
    title: "smart watch Model 1",
    image:
      "https://i.postimg.cc/R0wNmBcL/david-svihovec-T49gx2umonk-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 799,
    oldPrice: 899,
  },
  {
    id: 60,
    categories: "smart watch",
    title: "smart watch Model 2",
    image:
      "https://i.postimg.cc/qR0gM5wV/david-svihovec-t-Mea-U53-Hn1-Y-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 850,
    oldPrice: 950,
  },
  {
    id: 61,
    categories: "smart watch",
    title: "smart watch Model 3",
    image:
      "https://i.postimg.cc/Zn5R6vXw/david-svihovec-E1-AMQ35pjw-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.5,
    price: 780,
    oldPrice: 880,
  },
  {
    id: 62,
    categories: "smart watch",
    title: "smart watch Model 4",
    image:
      "https://i.postimg.cc/t4WXZzYX/eric-yu-Jqo-CRk-MAct-Y-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.4,
    price: 720,
    oldPrice: 820,
  },
  {
    id: 63,
    categories: "smart watch",
    title: "smart watch Model 5",
    image:
      "https://i.postimg.cc/jj6d9hb8/fabrice-mommer-DGcrlw7mx-Wo-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 890,
    oldPrice: 990,
  },
  {
    id: 64,
    categories: "smart watch",
    title: "smart watch Model 6",
    image:
      "https://i.postimg.cc/WbQN1ypW/julen-rey-azcona-E0msw66-Zw-ZU-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.5,
    price: 760,
    oldPrice: 860,
  },
  {
    id: 65,
    categories: "smart watch",
    title: "smart watch Model 7",
    image:
      "https://i.postimg.cc/sD1xXSYX/kenny-eliason-cu-Ljt-Xvo5bw-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 920,
    oldPrice: 1020,
  },
  {
    id: 66,
    categories: "smart watch",
    title: "smart watch Model 8",
    image:
      "https://i.postimg.cc/DwXzQTY3/klim-musalimov-m-LJNo6i4h-JI-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.4,
    price: 740,
    oldPrice: 840,
  },
  {
    id: 67,
    categories: "smart watch",
    title: "smart watch Model 9",
    image:
      "https://i.postimg.cc/yxx1D4S5/klim-musalimov-v-Rhb8b1-KW8-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.5,
    price: 800,
    oldPrice: 900,
  },
  {
    id: 68,
    categories: "smart watch",
    title: "smart watch Model 10",
    image:
      "https://i.postimg.cc/tTSyQSmz/lloyd-dirks-0vsk2-9dkqo-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 850,
    oldPrice: 950,
  },
  {
    id: 69,
    categories: "smart watch",
    title: "smart watch Model 11",
    image:
      "https://i.postimg.cc/QMqhSxQw/lloyd-dirks-qd-Y76g-IYbw8-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.5,
    price: 770,
    oldPrice: 870,
  },
  {
    id: 70,
    categories: "smart watch",
    title: "smart watch Model 12",
    image:
      "https://i.postimg.cc/7ZG5B7hc/luke-chesser-Jp-Y2r-PHFL8-E-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 900,
    oldPrice: 1000,
  },
  {
    id: 71,
    categories: "smart watch",
    title: "smart watch Model 13",
    image:
      "https://i.postimg.cc/RFXCCVqK/nils-huenerfuerst-WO4f-N-Li-Nl0-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.4,
    price: 720,
    oldPrice: 820,
  },
  {
    id: 72,
    categories: "smart watch",
    title: "smart watch Model 14",
    image:
      "https://i.postimg.cc/KzNjKDpK/pablo-figueroa-No-UQt-qd-Kjg-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.5,
    price: 760,
    oldPrice: 860,
  },
  {
    id: 73,
    categories: "smart watch",
    title: "smart watch Model 15",
    image:
      "https://i.postimg.cc/gJkd7F4J/pratik-prasad-FPEBZJLD8-Rs-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 840,
    oldPrice: 940,
  },
  {
    id: 74,
    categories: "smart watch",
    title: "smart watch Model 16",
    image:
      "https://i.postimg.cc/5tJfwFC8/pratik-prasad-w-Cce-AAw-Xzz0-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 890,
    oldPrice: 990,
  },
  {
    id: 75,
    categories: "smart watch",
    title: "smart watch Model 17",
    image:
      "https://i.postimg.cc/HsJWHmm8/sabina-0z-AHo-J1gn-Gg-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.4,
    price: 700,
    oldPrice: 800,
  },
  {
    id: 76,
    categories: "smart watch",
    title: "smart watch Model 18",
    image:
      "https://i.postimg.cc/rsZpjFkM/shawn-rain-6-Im-W5-VCW-w-I-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.5,
    price: 760,
    oldPrice: 860,
  },
  {
    id: 77,
    categories: "smart watch",
    title: "smart watch Model 19",
    image:
      "https://i.postimg.cc/BZ7Zd6rG/taylor-beach-vy-Jr3-Oy-S4-V8-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 850,
    oldPrice: 950,
  },
  {
    id: 78,
    categories: "smart watch",
    title: "smart watch Model 20",
    image:
      "https://i.postimg.cc/ZnQT378q/viktor-bystrov-a-Lrr-M7-VRz5-Q-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 920,
    oldPrice: 1020,
  },
  // __________Tablets___________
  {
    id: 79,
    categories: "tablet",
    title: "Tablet Model 1",
    image:
      "https://i.postimg.cc/JngGb5CP/brandon-romanchuk-qlyo-C7-Tz-Do-E-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.5,
    price: 500,
    oldPrice: 550,
  },
  {
    id: 80,
    categories: "tablet",
    title: "Tablet Model 2",
    image:
      "https://i.postimg.cc/FF7WbyLc/daniel-romero-B4hnt-JMwyu-M-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.4,
    price: 520,
    oldPrice: 580,
  },
  {
    id: 81,
    categories: "tablet",
    title: "Tablet Model 3",
    image:
      "https://i.postimg.cc/sX1cczvy/david-svihovec-p1-B6-G7acv-Z8-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 540,
    oldPrice: 590,
  },
  {
    id: 82,
    categories: "tablet",
    title: "Tablet Model 4",
    image:
      "https://i.postimg.cc/QtVF9nwF/david-svihovec-pb-s0-FYQZOo-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.3,
    price: 560,
    oldPrice: 610,
  },
  {
    id: 83,
    categories: "tablet",
    title: "Tablet Model 5",
    image:
      "https://i.postimg.cc/zXhx6qpG/dmitry-mashkin-p-NTL3r-OTH-E-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 580,
    oldPrice: 630,
  },
  {
    id: 84,
    categories: "tablet",
    title: "Tablet Model 6",
    image:
      "https://i.postimg.cc/j59h317f/henry-ascroft-7-OFnb7-NOvjw-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.2,
    price: 600,
    oldPrice: 650,
  },
  {
    id: 85,
    categories: "tablet",
    title: "Tablet Model 7",
    image:
      "https://i.postimg.cc/Hj1nNWxM/henry-ascroft-as-RF73-W3fd-Y-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.5,
    price: 620,
    oldPrice: 670,
  },
  {
    id: 86,
    categories: "tablet",
    title: "Tablet Model 8",
    image:
      "https://i.postimg.cc/2SF2jTsp/jakub-zerdzicki-68-ITk-Ii-VOHs-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.4,
    price: 640,
    oldPrice: 690,
  },
  {
    id: 87,
    categories: "tablet",
    title: "Tablet Model 9",
    image:
      "https://i.postimg.cc/PrD8Q9xZ/jakub-zerdzicki-i-Mre-BZE9n4k-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 660,
    oldPrice: 710,
  },
  {
    id: 88,
    categories: "tablet",
    title: "Tablet Model 10",
    image:
      "https://i.postimg.cc/vm0hfT83/jonas-leupe-Wmauj-u-L1c8-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.3,
    price: 680,
    oldPrice: 730,
  },
  {
    id: 89,
    categories: "tablet",
    title: "Tablet Model 11",
    image:
      "https://i.postimg.cc/HWRy5dpd/marek-levak-KOID4ns1-Ii4-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 700,
    oldPrice: 750,
  },
  {
    id: 90,
    categories: "tablet",
    title: "Tablet Model 12",
    image:
      "https://i.postimg.cc/yN1gBNTX/marek-levak-Rz3-Cm-Jpc-Lew-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.5,
    price: 720,
    oldPrice: 770,
  },
  {
    id: 91,
    categories: "tablet",
    title: "Tablet Model 13",
    image:
      "https://i.postimg.cc/59TPsXBr/matoo-studio-7-P2e-ZVar0-Nw-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.4,
    price: 740,
    oldPrice: 790,
  },
  {
    id: 92,
    categories: "tablet",
    title: "Tablet Model 14",
    image:
      "https://i.postimg.cc/7LKCLysv/max-schneider-5-Ja-N7r-Zh1ik-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.3,
    price: 760,
    oldPrice: 810,
  },
  {
    id: 93,
    categories: "tablet",
    title: "Tablet Model 15",
    image:
      "https://i.postimg.cc/T3qLZbn3/maxx-foto-2-Yp-Pzj8gn1-E-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.5,
    price: 780,
    oldPrice: 830,
  },
  {
    id: 94,
    categories: "tablet",
    title: "Tablet Model 16",
    image:
      "https://i.postimg.cc/ZqbjWpmW/roberto-nickson-h-Lg-Yt-X0r-Pgw-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 800,
    oldPrice: 850,
  },
  {
    id: 95,
    categories: "tablet",
    title: "Tablet Model 17",
    image:
      "https://i.postimg.cc/hvdhMQSg/samsung-memory-JDFtu-XWnz-AY-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.4,
    price: 820,
    oldPrice: 870,
  },
  {
    id: 96,
    categories: "tablet",
    title: "Tablet Model 18",
    image:
      "https://i.postimg.cc/PJwQgMWR/samsung-memory-o9zg-Emlbq-BY-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.5,
    price: 840,
    oldPrice: 890,
  },
  {
    id: 97,
    categories: "tablet",
    title: "Tablet Model 19",
    image:
      "https://i.postimg.cc/fWtCSMGf/surface-F4ott-WBn-Cp-M-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 860,
    oldPrice: 910,
  },
  {
    id: 98,
    categories: "tablet",
    title: "Tablet Model 20",
    image:
      "https://i.postimg.cc/HkC8ZzcN/tron-le-Dpz-LVRMNwc-Y-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 880,
    oldPrice: 930,
  },
  // ____________Mac_____________
  {
    id: 99,
    categories: "mac",
    title: "Mac Model 1",
    image:
      "https://i.postimg.cc/cJF6CH80/daniel-korpai-Hy-Twtsk8-Xq-A-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.8,
    price: 2200,
    oldPrice: 2400,
  },
  {
    id: 100,
    categories: "mac",
    title: "Mac Model 2",
    image:
      "https://i.postimg.cc/NjkV5Q3j/daniel-romero-K-a-NRqk-OTH0-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 2100,
    oldPrice: 2300,
  },
  {
    id: 101,
    categories: "mac",
    title: "Mac Model 3",
    image:
      "https://i.postimg.cc/g22yHdwJ/elise-bouet-URGhc8-HHd-FU-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 2500,
    oldPrice: 2700,
  },
  {
    id: 102,
    categories: "mac",
    title: "Mac Model 4",
    image:
      "https://i.postimg.cc/D04dscmc/fabio-alves-e-OU0-Ph-Qw-BKA-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.9,
    price: 2600,
    oldPrice: 2800,
  },
  {
    id: 103,
    categories: "mac",
    title: "Mac Model 5",
    image:
      "https://i.postimg.cc/wvLDjjrW/giorgio-trovato-8kr-X0-Hk-Xw8c-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.8,
    price: 2300,
    oldPrice: 2500,
  },
  {
    id: 104,
    categories: "mac",
    title: "Mac Model 6",
    image:
      "https://i.postimg.cc/YqkzjQMQ/jaime-marrero-QSZe7ao-A9e0-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 2400,
    oldPrice: 2600,
  },
  {
    id: 105,
    categories: "mac",
    title: "Mac Model 7",
    image:
      "https://i.postimg.cc/QMRpDTf9/julian-hochgesang-ps-GV5-Khidl-Y-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.9,
    price: 2800,
    oldPrice: 3000,
  },
  {
    id: 106,
    categories: "mac",
    title: "Mac Model 8",
    image:
      "https://i.postimg.cc/Zq9rXcxz/linus-mimietz-n-CYpagk-Ch-U-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 2100,
    oldPrice: 2300,
  },
  {
    id: 107,
    categories: "mac",
    title: "Mac Model 9",
    image:
      "https://i.postimg.cc/J7jQ1pV1/marten-bjork-Vh-Eszo-Hs07-Q-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.8,
    price: 2600,
    oldPrice: 2800,
  },
  {
    id: 108,
    categories: "mac",
    title: "Mac Model 10",
    image:
      "https://i.postimg.cc/YqwbgJfG/mehdi-saem-Hhny-TJj-FEe-E-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 2400,
    oldPrice: 2600,
  },
  {
    id: 109,
    categories: "mac",
    title: "Mac Model 11",
    image:
      "https://i.postimg.cc/mk9pR43R/moritz-kindler-cvw-Y7-R6-IIis-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.8,
    price: 2500,
    oldPrice: 2700,
  },
  {
    id: 110,
    categories: "mac",
    title: "Mac Model 12",
    image:
      "https://i.postimg.cc/DyqpM2yP/moritz-kindler-j-Li-Dlcm-wq-A-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.9,
    price: 2700,
    oldPrice: 2900,
  },
  {
    id: 111,
    categories: "mac",
    title: "Mac Model 13",
    image:
      "https://i.postimg.cc/SNr79jx3/moritz-kindler-tr-GRm4q-Ibbw-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 2300,
    oldPrice: 2500,
  },
  {
    id: 112,
    categories: "mac",
    title: "Mac Model 14",
    image:
      "https://i.postimg.cc/7ZH9t0Rq/omar-al-ghosson-Wrg-25q-Ew-XU-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.8,
    price: 2600,
    oldPrice: 2800,
  },
  {
    id: 113,
    categories: "mac",
    title: "Mac Model 15",
    image:
      "https://i.postimg.cc/qq2wSL0v/omar-al-ghosson-ZOXo-Ew-C9-D4-U-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.9,
    price: 2800,
    oldPrice: 3000,
  },
  {
    id: 114,
    categories: "mac",
    title: "Mac Model 16",
    image:
      "https://i.postimg.cc/8P8n4FDC/owen-spencer-zm-Kqf8-Wh-Ks-Y-unsplash-1.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 2200,
    oldPrice: 2400,
  },
  {
    id: 115,
    categories: "mac",
    title: "Mac Model 17",
    image:
      "https://i.postimg.cc/vZ2rPj9v/radek-grzybowski-e-BRTYyjwp-RY-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.8,
    price: 2500,
    oldPrice: 2700,
  },
  {
    id: 116,
    categories: "mac",
    title: "Mac Model 18",
    image:
      "https://i.postimg.cc/YSVxSVCS/sj-JOOUfcc8z-LE-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 2300,
    oldPrice: 2500,
  },
  {
    id: 117,
    categories: "mac",
    title: "Mac Model 19",
    image:
      "https://i.postimg.cc/8cddtzBF/theregisti-UIAGNe-MUHd-E-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.9,
    price: 2800,
    oldPrice: 3000,
  },

  // _____________Accessories________________
  {
    id: 118,
    categories: "accessories",
    title: "Accessory Model 1",
    image:
      "https://i.postimg.cc/q7Xj1QJB/6-9-oa-EKRUc-N5-V8-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 150,
    oldPrice: 180,
  },
  {
    id: 119,
    categories: "accessories",
    title: "Accessory Model 2",
    image:
      "https://i.postimg.cc/8zdRG5qt/aditya-sethia-oe-S2-Rtrc4-Oc-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 140,
    oldPrice: 170,
  },
  {
    id: 120,
    categories: "accessories",
    title: "Accessory Model 3",
    image:
      "https://i.postimg.cc/65vVHzzs/andrey-matveev-GQ-r-HFe-WUI-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.8,
    price: 160,
    oldPrice: 190,
  },
  {
    id: 121,
    categories: "accessories",
    title: "Accessory Model 4",
    image:
      "https://i.postimg.cc/3R89VpNX/anthony-roberts-W-DCDWCL3-Wo-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 170,
    oldPrice: 200,
  },
  {
    id: 122,
    categories: "accessories",
    title: "Accessory Model 5",
    image:
      "https://i.postimg.cc/vHghJGYN/david-griffiths-v7v-DNSt-U2-Ak-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.9,
    price: 180,
    oldPrice: 210,
  },
  {
    id: 123,
    categories: "accessories",
    title: "Accessory Model 6",
    image:
      "https://i.postimg.cc/tg2F1cR6/declan-sun-6-S7-SY2p-c-As-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.8,
    price: 150,
    oldPrice: 180,
  },
  {
    id: 124,
    categories: "accessories",
    title: "Accessory Model 7",
    image:
      "https://i.postimg.cc/T1yjvc6D/filtergrade-o-Py-Acpk-Qch0-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 160,
    oldPrice: 190,
  },
  {
    id: 125,
    categories: "accessories",
    title: "Accessory Model 8",
    image:
      "https://i.postimg.cc/Bvqxn33s/homemade-media-6l5z2-EPrn-Fc-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 170,
    oldPrice: 200,
  },
  {
    id: 126,
    categories: "accessories",
    title: "Accessory Model 9",
    image:
      "https://i.postimg.cc/mg7wrVF3/joseph-greve-BPJKc4r7-eo-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.8,
    price: 180,
    oldPrice: 210,
  },
  {
    id: 127,
    categories: "accessories",
    title: "Accessory Model 10",
    image:
      "https://i.postimg.cc/hPksgNhP/joseph-greve-rst3-YOh6-LXA-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.9,
    price: 150,
    oldPrice: 180,
  },
  {
    id: 128,
    categories: "accessories",
    title: "Accessory Model 11",
    image:
      "https://i.postimg.cc/Kz0Q2z3d/karmishth-tandel-Yh3-PGpkwk-g-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 160,
    oldPrice: 190,
  },
  {
    id: 129,
    categories: "accessories",
    title: "Accessory Model 12",
    image:
      "https://i.postimg.cc/QMsqK5p2/luke-hodde-Z-Uu-XG6ia-A8-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 170,
    oldPrice: 200,
  },
  {
    id: 130,
    categories: "accessories",
    title: "Accessory Model 13",
    image:
      "https://i.postimg.cc/dQXmmg2m/mahrous-houses-5-Ao-Oejj-RUr-A-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.8,
    price: 180,
    oldPrice: 210,
  },
  {
    id: 131,
    categories: "accessories",
    title: "Accessory Model 14",
    image:
      "https://i.postimg.cc/nzhY0JST/mahrous-houses-d-Xk-Nl-C5wyk-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.9,
    price: 150,
    oldPrice: 180,
  },
  {
    id: 132,
    categories: "accessories",
    title: "Accessory Model 15",
    image:
      "https://i.postimg.cc/6qDrWGW1/markus-spiske-i-ABDzn-UDy6c-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 160,
    oldPrice: 190,
  },
  {
    id: 133,
    categories: "accessories",
    title: "Accessory Model 16",
    image:
      "https://i.postimg.cc/131Gb6Y8/rezwan-ahmed-CXzn-HE1p-Kx-E-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 170,
    oldPrice: 200,
  },
  {
    id: 134,
    categories: "accessories",
    title: "Accessory Model 17",
    image:
      "https://i.postimg.cc/FRCb6B2v/simon-kadula-gknd-M1-Gv-SA-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.8,
    price: 180,
    oldPrice: 210,
  },
  {
    id: 135,
    categories: "accessories",
    title: "Accessory Model 18",
    image:
      "https://i.postimg.cc/0NqVGhqH/tai-bui-Q-x-Gz9-NOVOE-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.9,
    price: 150,
    oldPrice: 180,
  },
  {
    id: 136,
    categories: "accessories",
    title: "Accessory Model 19",
    image:
      "https://i.postimg.cc/WbhYsMnS/tao-yuan-p-Zvd-CAc2-M-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 160,
    oldPrice: 190,
  },
  {
    id: 137,
    categories: "accessories",
    title: "Accessory Model 20",
    image:
      "https://i.postimg.cc/0Nf0YQnb/ty-feague-zc-Ra-KHDP83-I-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 170,
    oldPrice: 200,
  },

  // ___________SoundBox____________
  {
    id: 138,
    categories: "soundbox",
    title: "Soundbox Model 1",
    image:
      "https://i.postimg.cc/qBjnjS2Z/2h-media-mv-Oh-QZX-LBk-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.8,
    price: 350,
    oldPrice: 400,
  },
  {
    id: 139,
    categories: "soundbox",
    title: "Soundbox Model 2",
    image:
      "https://i.postimg.cc/KzQKp33g/adam-birkett-v-ISNAATFXl-E-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 320,
    oldPrice: 370,
  },
  {
    id: 140,
    categories: "soundbox",
    title: "Soundbox Model 3",
    image:
      "https://i.postimg.cc/vTQrcdf5/andrey-matveev-sozo-YOGrb-Xg-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 300,
    oldPrice: 350,
  },
  {
    id: 141,
    categories: "soundbox",
    title: "Soundbox Model 4",
    image:
      "https://i.postimg.cc/BvKczpJP/arthur-a-Zp-QTAz0-Jc2-E-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.9,
    price: 380,
    oldPrice: 430,
  },
  {
    id: 142,
    categories: "soundbox",
    title: "Soundbox Model 5",
    image:
      "https://i.postimg.cc/5tdFXVMj/c-d-x-d-Bwadh-Wa-l-I-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.8,
    price: 340,
    oldPrice: 390,
  },
  {
    id: 143,
    categories: "soundbox",
    title: "Soundbox Model 6",
    image:
      "https://i.postimg.cc/g26Zc0Qf/dan-farrell-Fn-R2-U1l-Xs-BQ-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 310,
    oldPrice: 360,
  },
  {
    id: 144,
    categories: "soundbox",
    title: "Soundbox Model 7",
    image:
      "https://i.postimg.cc/sX3QJ4xr/ervo-rocks-Zam8-Tv-Eg-N5o-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 300,
    oldPrice: 350,
  },
  {
    id: 145,
    categories: "soundbox",
    title: "Soundbox Model 8",
    image:
      "https://i.postimg.cc/wjSDDNDq/howard-bouchevereau-5ba6j8d-o-XY-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.9,
    price: 390,
    oldPrice: 440,
  },
  {
    id: 146,
    categories: "soundbox",
    title: "Soundbox Model 9",
    image:
      "https://i.postimg.cc/xCGGfdJ0/kreeson-naraidoo-Dwz-Cmllk3w-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.8,
    price: 350,
    oldPrice: 400,
  },
  {
    id: 147,
    categories: "soundbox",
    title: "Soundbox Model 10",
    image:
      "https://i.postimg.cc/x8CXwjLp/luke-peterson-l-UMj2-Zv5-HUE-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 320,
    oldPrice: 370,
  },
  {
    id: 148,
    categories: "soundbox",
    title: "Soundbox Model 11",
    image:
      "https://i.postimg.cc/JhZZxhQb/omid-armin-g-SZCLs-E7ysc-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 300,
    oldPrice: 350,
  },
  {
    id: 149,
    categories: "soundbox",
    title: "Soundbox Model 12",
    image:
      "https://i.postimg.cc/52HwHgYK/omid-armin-G-GFA2grq-k-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.9,
    price: 380,
    oldPrice: 430,
  },
  {
    id: 150,
    categories: "soundbox",
    title: "Soundbox Model 13",
    image:
      "https://i.postimg.cc/Fs6SQSWy/petri-r-Qsj-Lj-Efhl-Zg-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.8,
    price: 340,
    oldPrice: 390,
  },
  {
    id: 151,
    categories: "soundbox",
    title: "Soundbox Model 14",
    image:
      "https://i.postimg.cc/yY8hKsVH/phuc-khang-mobile-fq6-KYq6-Q16o-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 310,
    oldPrice: 360,
  },
  {
    id: 152,
    categories: "soundbox",
    title: "Soundbox Model 15",
    image:
      "https://i.postimg.cc/T1CrbHJF/prashant-Jm-pr52-Rl7-Y-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 300,
    oldPrice: 350,
  },
  {
    id: 153,
    categories: "soundbox",
    title: "Soundbox Model 16",
    image:
      "https://i.postimg.cc/02jS3nf5/sam-grozyan-P7-KF3c-TRKc-E-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.9,
    price: 390,
    oldPrice: 440,
  },
  {
    id: 154,
    categories: "soundbox",
    title: "Soundbox Model 17",
    image:
      "https://i.postimg.cc/4dGtST8j/sasun-bughdaryan-y2bp-SSu-GR98-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.8,
    price: 350,
    oldPrice: 400,
  },
  {
    id: 155,
    categories: "soundbox",
    title: "Soundbox Model 18",
    image:
      "https://i.postimg.cc/wT4XTZvs/servet-photograph-vya2wf-Wcizo-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 320,
    oldPrice: 370,
  },
  {
    id: 156,
    categories: "soundbox",
    title: "Soundbox Model 19",
    image:
      "https://i.postimg.cc/VNq0MVYg/tomasz-gawlowski-YDZPdqv3-Fc-A-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 300,
    oldPrice: 350,
  },

  // ____________Smart Gadget______________
  {
    id: 158,
    categories: "smart gadget",
    title: "Smart Gadget Model 1",
    image:
      "https://i.postimg.cc/4Nx0SDqK/aaron-burden-y-Fn-X8-Da-C3-UM-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.8,
    price: 520,
    oldPrice: 600,
  },
  {
    id: 159,
    categories: "smart gadget",
    title: "Smart Gadget Model 2",
    image:
      "https://i.postimg.cc/FFWp77CR/charlie-firth-e8dgy7h-G6-C8-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 450,
    oldPrice: 500,
  },
  {
    id: 160,
    categories: "smart gadget",
    title: "Smart Gadget Model 3",
    image:
      "https://i.postimg.cc/tR5fDqSQ/diana-macesanu-3ci-Hxbx9-H0-U-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 390,
    oldPrice: 450,
  },
  {
    id: 161,
    categories: "smart gadget",
    title: "Smart Gadget Model 4",
    image:
      "https://i.postimg.cc/BvH7F4Lz/dose-media-KFWCjf-KIQag-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.5,
    price: 340,
    oldPrice: 400,
  },
  {
    id: 162,
    categories: "smart gadget",
    title: "Smart Gadget Model 5",
    image:
      "https://i.postimg.cc/kXHThBWZ/girl-with-red-hat-e60zb-IILCnk-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.9,
    price: 600,
    oldPrice: 670,
  },
  {
    id: 163,
    categories: "smart gadget",
    title: "Smart Gadget Model 6",
    image:
      "https://i.postimg.cc/X71PS26s/ian-baldwin-Cfu0m-T9b-RJw-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.4,
    price: 310,
    oldPrice: 360,
  },
  {
    id: 164,
    categories: "smart gadget",
    title: "Smart Gadget Model 7",
    image:
      "https://i.postimg.cc/LsKN2wC3/insung-yoon-HMo-Leq-W-YQ-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.8,
    price: 480,
    oldPrice: 530,
  },
  {
    id: 165,
    categories: "smart gadget",
    title: "Smart Gadget Model 8",
    image:
      "https://i.postimg.cc/3rnSmLN3/insung-yoon-l-Qa54-NKmg-JQ-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 420,
    oldPrice: 490,
  },
  {
    id: 166,
    categories: "smart gadget",
    title: "Smart Gadget Model 9",
    image:
      "https://i.postimg.cc/GmZS9H2Y/jared-brashier-du-NHkm-Sk-W6-M-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 350,
    oldPrice: 400,
  },
  {
    id: 167,
    categories: "smart gadget",
    title: "Smart Gadget Model 10",
    image:
      "https://i.postimg.cc/HkJhpQpd/jonathan-lampel-L9wr-EGJj-Rdo-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.9,
    price: 650,
    oldPrice: 720,
  },
  {
    id: 168,
    categories: "smart gadget",
    title: "Smart Gadget Model 11",
    image:
      "https://i.postimg.cc/NfFN412m/krishna-dev-II8b68-NHZk-Y-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.8,
    price: 570,
    oldPrice: 640,
  },
  {
    id: 169,
    categories: "smart gadget",
    title: "Smart Gadget Model 12",
    image:
      "https://i.postimg.cc/d3H5F0ph/lana-mattice-8-L044-OEc-GDY-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.5,
    price: 310,
    oldPrice: 370,
  },
  {
    id: 170,
    categories: "smart gadget",
    title: "Smart Gadget Model 13",
    image:
      "https://i.postimg.cc/sxDTbW6F/lana-mattice-mo-Lwa-Yt9-E0-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 360,
    oldPrice: 420,
  },
  {
    id: 171,
    categories: "smart gadget",
    title: "Smart Gadget Model 14",
    image:
      "https://i.postimg.cc/bvxLJg4c/leonard-reeb-Ed-Gi-Mi-Rvoro-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 410,
    oldPrice: 480,
  },
  {
    id: 172,
    categories: "smart gadget",
    title: "Smart Gadget Model 15",
    image:
      "https://i.postimg.cc/Y09xdH0M/logan-weaver-lgnwvr-gb-Wf-Ge1-Dm-Dw-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.9,
    price: 680,
    oldPrice: 750,
  },
  {
    id: 173,
    categories: "smart gadget",
    title: "Smart Gadget Model 16",
    image:
      "https://i.postimg.cc/P58SGT4q/logan-weaver-lgnwvr-s-Vwu-CEJp-Jo-A-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.8,
    price: 530,
    oldPrice: 600,
  },
  {
    id: 174,
    categories: "smart gadget",
    title: "Smart Gadget Model 17",
    image:
      "https://i.postimg.cc/DZcCC6cd/matteo-bernardis-QKp-Q40ai-Tj0-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 360,
    oldPrice: 420,
  },
  {
    id: 175,
    categories: "smart gadget",
    title: "Smart Gadget Model 18",
    image:
      "https://i.postimg.cc/RhXD0d6V/mitch-nielsen-p-Wt-NPCpv-VA8-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.5,
    price: 340,
    oldPrice: 390,
  },
  {
    id: 176,
    categories: "smart gadget",
    title: "Smart Gadget Model 19",
    image:
      "https://i.postimg.cc/T1RsGFP4/ricardo-gomez-angel-d8dn-BSJWdk4-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 430,
    oldPrice: 500,
  },
  {
    id: 177,
    categories: "smart gadget",
    title: "Smart Gadget Model 20",
    image:
      "https://i.postimg.cc/hjKs7xqJ/yunfan-xu-50g-Vhy-Mj9z-Q-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.8,
    price: 560,
    oldPrice: 630,
  },

  // _____________Monitor______________
  {
    id: 178,
    categories: "monitor",
    title: "Monitor Model 1",
    image:
      "https://i.postimg.cc/Qtpg8JY9/carl-heyerdahl-KE0n-C8-58-MQ-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.9,
    price: 850,
    oldPrice: 920,
  },
  {
    id: 179,
    categories: "monitor",
    title: "Monitor Model 2",
    image:
      "https://i.postimg.cc/G3Fzdd67/charles-patterson-5-LWQapj-G-Q-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 780,
    oldPrice: 850,
  },
  {
    id: 180,
    categories: "monitor",
    title: "Monitor Model 3",
    image:
      "https://i.postimg.cc/7hw3fJjB/daniel-korpai-8-GDCz-Wrc-E3-M-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.8,
    price: 960,
    oldPrice: 1040,
  },
  {
    id: 181,
    categories: "monitor",
    title: "Monitor Model 4",
    image:
      "https://i.postimg.cc/Bnk22VdP/daniel-korpai-iop-ITwy-Uc-TA-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 720,
    oldPrice: 800,
  },
  {
    id: 182,
    categories: "monitor",
    title: "Monitor Model 5",
    image:
      "https://i.postimg.cc/RZDLXFnF/danny-feng-3-En7-Aaqiw8-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.9,
    price: 1100,
    oldPrice: 1180,
  },
  {
    id: 183,
    categories: "monitor",
    title: "Monitor Model 6",
    image:
      "https://i.postimg.cc/wBRcPphk/jorge-ramirez-SVp-Wtj-Xm-LZg-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.8,
    price: 890,
    oldPrice: 970,
  },
  {
    id: 184,
    categories: "monitor",
    title: "Monitor Model 7",
    image:
      "https://i.postimg.cc/SxJW2htp/kitai-zhvaeh-R9r-A-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 940,
    oldPrice: 1010,
  },
  {
    id: 185,
    categories: "monitor",
    title: "Monitor Model 8",
    image:
      "https://i.postimg.cc/gJqRFkr3/linus-mimietz-gvpt-Kmonylk-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.8,
    price: 990,
    oldPrice: 1070,
  },
  {
    id: 186,
    categories: "monitor",
    title: "Monitor Model 9",
    image:
      "https://i.postimg.cc/wMQkVQh8/mediamodifier-qz-Y7-Ca0yrm4-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 880,
    oldPrice: 950,
  },
  {
    id: 187,
    categories: "monitor",
    title: "Monitor Model 10",
    image:
      "https://i.postimg.cc/j5VQYFcY/niclas-illg-wz-VQp-NRIHg-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.9,
    price: 1020,
    oldPrice: 1100,
  },
  {
    id: 188,
    categories: "monitor",
    title: "Monitor Model 11",
    image:
      "https://i.postimg.cc/NGk8ZbrZ/niclas-illg-z-EBq-F-E2-FIY-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 950,
    oldPrice: 1030,
  },
  {
    id: 189,
    categories: "monitor",
    title: "Monitor Model 12",
    image:
      "https://i.postimg.cc/k5SKsym1/nicolas-gonzalez-183-F-v-Na-N8-A-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.8,
    price: 910,
    oldPrice: 990,
  },
  {
    id: 190,
    categories: "monitor",
    title: "Monitor Model 13",
    image:
      "https://i.postimg.cc/zXq7f4rJ/nubelson-fernandes-Az-HPen-cymc-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.9,
    price: 1000,
    oldPrice: 1080,
  },
  {
    id: 191,
    categories: "monitor",
    title: "Monitor Model 14",
    image:
      "https://i.postimg.cc/TYQ95Qdn/personalgraphic-com-uqd-EKKUh-Pf-Q-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.8,
    price: 970,
    oldPrice: 1050,
  },
  {
    id: 192,
    categories: "monitor",
    title: "Monitor Model 15",
    image:
      "https://i.postimg.cc/zXdCGB7j/polina-kuzovkova-M9-d-SG3-Iswg-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.6,
    price: 890,
    oldPrice: 960,
  },
  {
    id: 193,
    categories: "monitor",
    title: "Monitor Model 16",
    image:
      "https://i.postimg.cc/vBd9N68Q/quaritsch-photography-m2zu-B8-Dqwy-M-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.7,
    price: 930,
    oldPrice: 1010,
  },
  {
    id: 194,
    categories: "monitor",
    title: "Monitor Model 17",
    image:
      "https://i.postimg.cc/Hkxtw5nR/radoslav-bali-tk-Rrm-Yo-N2to-unsplash.jpg?w=300&format=webp&quality=80",
    rating: 4.8,
    price: 960,
    oldPrice: 1040,
  },
  {
    id: 195,
    categories: "monitor",
    title: "Monitor Model 18",
    image: "https://i.postimg.cc/7YP1473h/rohit-KZnfwqi-B0-U-unsplash.jpg",
    rating: 4.7,
    price: 910,
    oldPrice: 980,
  },
  {
    id: 196,
    categories: "monitor",
    title: "Monitor Model 19",
    image: "https://i.postimg.cc/C5gNkQns/sameer-BOy-Su9-Zf-Fp-I-unsplash.jpg",
    rating: 4.9,
    price: 1050,
    oldPrice: 1130,
  },
  {
    id: 197,
    categories: "monitor",
    title: "Monitor Model 20",
    image:
      "https://i.postimg.cc/vThW9HsG/seyed-sina-fazeli-XP9-JF6jy-RGc-unsplash.jpg",
    rating: 4.8,
    price: 980,
    oldPrice: 1060,
  },
  // __________Mac Pro (Next Batch)______________
  {
    id: 198,
    categories: "macPro",
    title: "Mac Pro 2024 (M3 Ultra)",
    image:
      "https://www.apple.com/newsroom/images/product/mac-pro/standard/mac-pro-m3-ultra-hero_2024.jpg",
    rating: 4.9,
    price: 9500,
    oldPrice: 10500,
  },
  {
    id: 199,
    categories: "macPro",
    title: "Mac Pro Rack Edition (M3)",
    image:
      "https://www.apple.com/newsroom/images/product/mac-pro/standard/mac-pro-rack-m3_2024.jpg",
    rating: 4.8,
    price: 11500,
    oldPrice: 13000,
  },
  {
    id: 200,
    categories: "macPro",
    title: "Mac Pro (M3 Ultra, Max GPU)",
    image:
      "https://www.apple.com/newsroom/images/product/mac-pro/standard/mac-pro-m3-ultra-gpu_2024.jpg",
    rating: 5.0,
    price: 14000,
    oldPrice: 15500,
  },
  {
    id: 201,
    categories: "macPro",
    title: "Mac Pro (Afterburner Pro Edition)",
    image:
      "https://www.apple.com/newsroom/images/product/mac-pro/standard/mac-pro-afterburner-pro_2024.jpg",
    rating: 4.7,
    price: 12000,
    oldPrice: 13500,
  },
  {
    id: 202,
    categories: "macPro",
    title: "Mac Pro (High-Memory Config 1TB RAM)",
    image:
      "https://www.apple.com/newsroom/images/product/mac-pro/standard/mac-pro-1tb-ram_2024.jpg",
    rating: 4.9,
    price: 15000,
    oldPrice: 16500,
  },
  {
    id: 203,
    categories: "macPro",
    title: "Mac Pro (Dual GPU, AI Optimized)",
    image:
      "https://www.apple.com/newsroom/images/product/mac-pro/standard/mac-pro-ai-dual-gpu_2024.jpg",
    rating: 4.8,
    price: 13500,
    oldPrice: 15000,
  },
  {
    id: 204,
    categories: "macPro",
    title: "Mac Pro (Pro Studio Max Edition)",
    image:
      "https://www.apple.com/newsroom/images/product/mac-pro/standard/mac-pro-pro-studio_2024.jpg",
    rating: 5.0,
    price: 16000,
    oldPrice: 17800,
  },
  {
    id: 205,
    categories: "macPro",
    title: "Mac Pro (Entry-Level M3 Ultra)",
    image:
      "https://www.apple.com/newsroom/images/product/mac-pro/standard/mac-pro-entry-m3_2024.jpg",
    rating: 4.6,
    price: 8500,
    oldPrice: 9500,
  },
  {
    id: 206,
    categories: "macPro",
    title: "Mac Pro (High-Bandwidth Memory, AI Ready)",
    image:
      "https://www.apple.com/newsroom/images/product/mac-pro/standard/mac-pro-hbm-ai_2024.jpg",
    rating: 4.9,
    price: 12500,
    oldPrice: 14000,
  },
  {
    id: 207,
    categories: "macPro",
    title: "Mac Pro (ProRes X Workflow)",
    image:
      "https://www.apple.com/newsroom/images/product/mac-pro/standard/mac-pro-proresx_2024.jpg",
    rating: 4.8,
    price: 14500,
    oldPrice: 16000,
  },
  {
    id: 208,
    categories: "macPro",
    title: "Mac Pro (Scientific Research Edition)",
    image:
      "https://www.apple.com/newsroom/images/product/mac-pro/standard/mac-pro-scientific-2024.jpg",
    rating: 4.7,
    price: 17000,
    oldPrice: 19000,
  },
  {
    id: 209,
    categories: "macPro",
    title: "Mac Pro (Ultimate Config M3 Ultra)",
    image:
      "https://www.apple.com/newsroom/images/product/mac-pro/standard/mac-pro-ultimate-m3_2024.jpg",
    rating: 5.0,
    price: 20000,
    oldPrice: 22000,
  },
  // __________Brand PC______________
  {
    id: 210,
    categories: "brandPc",
    title: "Dell XPS Desktop 8960",
    image:
      "https://i.dell.com/sites/csimages/Video_Imagery/all/xps-desktop-8960.png",
    rating: 4.8,
    price: 2200,
    oldPrice: 2500,
  },
  {
    id: 211,
    categories: "brandPc",
    title: "HP Omen 45L Gaming Desktop",
    image:
      "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08566721.png",
    rating: 4.7,
    price: 2600,
    oldPrice: 2900,
  },
  {
    id: 212,
    categories: "brandPc",
    title: "Lenovo Legion Tower 7i",
    image: "https://p4-ofp.static.pub/medias/lenovo-legion-t7-tower-7i.png",
    rating: 4.9,
    price: 2800,
    oldPrice: 3100,
  },
  {
    id: 213,
    categories: "brandPc",
    title: "ASUS ROG Strix G35",
    image: "https://dlcdnwebimgs.asus.com/gain/ba8b16c2-rog-strix-g35.png",
    rating: 4.8,
    price: 2700,
    oldPrice: 2950,
  },
  {
    id: 214,
    categories: "brandPc",
    title: "Acer Predator Orion 7000",
    image:
      "https://static.acer.com/up/Resource/Acer/Desktops/Predator_Orion_7000/20230807/Predator-Orion-7000.png",
    rating: 4.7,
    price: 2500,
    oldPrice: 2800,
  },
  {
    id: 215,
    categories: "brandPc",
    title: "MSI Infinite RS 13th",
    image:
      "https://asset.msi.com/resize/image/global/product/product_1676019321.png",
    rating: 4.6,
    price: 2400,
    oldPrice: 2700,
  },
  {
    id: 216,
    categories: "brandPc",
    title: "Dell Alienware Aurora R15",
    image:
      "https://i.dell.com/sites/csimages/App-Merchandizing_Imagery/all/alienware-aurora-r15.png",
    rating: 4.9,
    price: 3000,
    oldPrice: 3300,
  },
  {
    id: 217,
    categories: "brandPc",
    title: "HP Elite Tower 800 G9",
    image:
      "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08045621.png",
    rating: 4.6,
    price: 1800,
    oldPrice: 2000,
  },
  {
    id: 218,
    categories: "brandPc",
    title: "Lenovo ThinkCentre M90t",
    image: "https://p1-ofp.static.pub/medias/lenovo-thinkcentre-m90t.png",
    rating: 4.7,
    price: 1600,
    oldPrice: 1900,
  },
  {
    id: 219,
    categories: "brandPc",
    title: "ASUS ExpertCenter D9 Tower",
    image: "https://dlcdnwebimgs.asus.com/gain/5e7fd2d8-expertcenter-d9.png",
    rating: 4.5,
    price: 1700,
    oldPrice: 1950,
  },
  {
    id: 220,
    categories: "brandPc",
    title: "Acer Veriton X670",
    image:
      "https://static.acer.com/up/Resource/Acer/Desktop/Veriton/Veriton_X670/20230801/Veriton-X670.png",
    rating: 4.6,
    price: 1500,
    oldPrice: 1750,
  },
  {
    id: 221,
    categories: "brandPc",
    title: "MSI PRO DP21",
    image:
      "https://asset.msi.com/resize/image/global/product/product_1674019110.png",
    rating: 4.5,
    price: 1300,
    oldPrice: 1550,
  },
  {
    id: 222,
    categories: "brandPc",
    title: "Dell OptiPlex 7010 Tower",
    image:
      "https://i.dell.com/sites/csimages/App-Merchandizing_Imagery/all/optiplex-7010.png",
    rating: 4.6,
    price: 1400,
    oldPrice: 1650,
  },
  {
    id: 223,
    categories: "brandPc",
    title: "HP Z2 Tower G9 Workstation",
    image:
      "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08347421.png",
    rating: 4.8,
    price: 2100,
    oldPrice: 2350,
  },
  {
    id: 224,
    categories: "brandPc",
    title: "Lenovo ThinkStation P620",
    image: "https://p4-ofp.static.pub/medias/lenovo-thinkstation-p620.png",
    rating: 4.9,
    price: 3200,
    oldPrice: 3500,
  },
  {
    id: 225,
    categories: "brandPc",
    title: "ASUS ProArt Station PD5",
    image: "https://dlcdnwebimgs.asus.com/gain/6c84938f-proart-pd5.png",
    rating: 4.7,
    price: 2300,
    oldPrice: 2600,
  },
  {
    id: 226,
    categories: "brandPc",
    title: "Acer Aspire TC-1760",
    image:
      "https://static.acer.com/up/Resource/Acer/Desktop/Aspire/Aspire-TC-1760/20230807/Aspire-TC-1760.png",
    rating: 4.5,
    price: 900,
    oldPrice: 1100,
  },
  {
    id: 227,
    categories: "brandPc",
    title: "MSI Creator P100X",
    image:
      "https://asset.msi.com/resize/image/global/product/product_1676019871.png",
    rating: 4.8,
    price: 2500,
    oldPrice: 2800,
  },
  {
    id: 228,
    categories: "brandPc",
    title: "Dell Precision 5860 Tower",
    image:
      "https://i.dell.com/sites/csimages/App-Merchandizing_Imagery/all/precision-5860-tower.png",
    rating: 4.9,
    price: 3500,
    oldPrice: 3800,
  },
  {
    id: 229,
    categories: "brandPc",
    title: "HP Envy Desktop TE02",
    image:
      "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08567421.png",
    rating: 4.6,
    price: 1200,
    oldPrice: 1450,
  },
  // __________Gaming PC______________
{
  id: 230,
  categories: "gamingPc",
  title: "Alienware Aurora R15",
  image: "https://i.dell.com/sites/csimages/App-Merchandizing_Imagery/all/alienware-aurora-r15.png",
  rating: 4.9,
  price: 3200,
  oldPrice: 3500,
},
{
  id: 231,
  categories: "gamingPc",
  title: "ASUS ROG Strix G16",
  image: "https://dlcdnwebimgs.asus.com/gain/0f2f4272-rog-strix-g16.png",
  rating: 4.8,
  price: 2800,
  oldPrice: 3100,
},
{
  id: 232,
  categories: "gamingPc",
  title: "MSI MEG Trident X2",
  image: "https://asset.msi.com/resize/image/global/product/product_1681964309.png",
  rating: 4.9,
  price: 3400,
  oldPrice: 3700,
},
{
  id: 233,
  categories: "gamingPc",
  title: "HP Omen 45L",
  image: "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08566721.png",
  rating: 4.7,
  price: 3000,
  oldPrice: 3300,
},
{
  id: 234,
  categories: "gamingPc",
  title: "Lenovo Legion Tower 7i",
  image: "https://p4-ofp.static.pub/medias/lenovo-legion-t7-tower-7i.png",
  rating: 4.8,
  price: 2900,
  oldPrice: 3200,
},
{
  id: 235,
  categories: "gamingPc",
  title: "Acer Predator Orion 7000",
  image: "https://static.acer.com/up/Resource/Acer/Desktops/Predator_Orion_7000/20230807/Predator-Orion-7000.png",
  rating: 4.7,
  price: 3100,
  oldPrice: 3400,
},
{
  id: 236,
  categories: "gamingPc",
  title: "Corsair Vengeance i7400",
  image: "https://cwsmgmt.corsair.com/pdp/vengeance-i7400-configurator.png",
  rating: 4.8,
  price: 3300,
  oldPrice: 3600,
},
{
  id: 237,
  categories: "gamingPc",
  title: "NZXT Player Two Prime",
  image: "https://nzxt.com/assets/cms/34299/1682532680-player-two-prime.png",
  rating: 4.6,
  price: 2600,
  oldPrice: 2900,
},
{
  id: 238,
  categories: "gamingPc",
  title: "Alienware Aurora R16",
  image: "https://i.dell.com/sites/csimages/App-Merchandizing_Imagery/all/alienware-aurora-r16.png",
  rating: 5.0,
  price: 3500,
  oldPrice: 3800,
},
{
  id: 239,
  categories: "gamingPc",
  title: "ASUS ROG Huracan G21",
  image: "https://dlcdnwebimgs.asus.com/gain/9d3a43f8-rog-huracan-g21.png",
  rating: 4.7,
  price: 2700,
  oldPrice: 3000,
},
{
  id: 240,
  categories: "gamingPc",
  title: "MSI Infinite RS 13th",
  image: "https://asset.msi.com/resize/image/global/product/product_1676019321.png",
  rating: 4.7,
  price: 2800,
  oldPrice: 3100,
},
{
  id: 241,
  categories: "gamingPc",
  title: "HP Omen 25L",
  image: "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08566821.png",
  rating: 4.5,
  price: 2000,
  oldPrice: 2300,
},
{
  id: 242,
  categories: "gamingPc",
  title: "Lenovo Legion Tower 5i",
  image: "https://p2-ofp.static.pub/medias/lenovo-legion-tower-5i.png",
  rating: 4.6,
  price: 1900,
  oldPrice: 2200,
},
{
  id: 243,
  categories: "gamingPc",
  title: "Acer Nitro 50",
  image: "https://static.acer.com/up/Resource/Acer/Desktops/Nitro/Nitro50/20230807/Nitro-50.png",
  rating: 4.5,
  price: 1500,
  oldPrice: 1800,
},
{
  id: 244,
  categories: "gamingPc",
  title: "Corsair Vengeance a7200",
  image: "https://cwsmgmt.corsair.com/pdp/vengeance-a7200.png",
  rating: 4.7,
  price: 2800,
  oldPrice: 3100,
},
{
  id: 245,
  categories: "gamingPc",
  title: "NZXT Player Three",
  image: "https://nzxt.com/assets/cms/34299/1682532680-player-three.png",
  rating: 4.6,
  price: 2900,
  oldPrice: 3200,
},
{
  id: 246,
  categories: "gamingPc",
  title: "Alienware Aurora Ryzen R14",
  image: "https://i.dell.com/sites/csimages/App-Merchandizing_Imagery/all/alienware-aurora-ryzen-r14.png",
  rating: 4.8,
  price: 3100,
  oldPrice: 3400,
},
{
  id: 247,
  categories: "gamingPc",
  title: "ASUS ROG Strix G35",
  image: "https://dlcdnwebimgs.asus.com/gain/ba8b16c2-rog-strix-g35.png",
  rating: 4.9,
  price: 3000,
  oldPrice: 3300,
},
{
  id: 248,
  categories: "gamingPc",
  title: "MSI Aegis RS 13NUE",
  image: "https://asset.msi.com/resize/image/global/product/product_1681452361.png",
  rating: 4.7,
  price: 2600,
  oldPrice: 2900,
},
{
  id: 249,
  categories: "gamingPc",
  title: "HP Victus 15L",
  image: "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08566921.png",
  rating: 4.5,
  price: 1400,
  oldPrice: 1650,
},

];
